DOMAIN = "shmu_alerts"

DISTRICTS = {
    "BA": "Bratislava",
    "BB": "Banská Bystrica",
    "BS": "Banská Štiavnica",
    "BN": "Bánovce nad Bebravou",
    "BR": "Brezno",
    "BY": "Bytča",
    "CA": "Čadca",
    "DK": "Dolný Kubín",
    "DS": "Dunajská Streda",
    "GA": "Galanta",
    "GL": "Gelnica",
    "HC": "Hlohovec",
    "HE": "Humenné",
    "IL": "Ilava",
    "KE": "Košice",
    "KEO": "Košice-okolie",
    "KK": "Kežmarok",
    "KM": "Kysucké Nové Mesto",
    "LC": "Lučenec",
    "LE": "Levoča",
    "LV": "Levice",
    "LM": "Liptovský Mikuláš",
    "MA": "Malacky",
    "MI": "Michalovce",
    "ML": "Medzilaborce",
    "MT": "Martin",
    "NR": "Nitra",
    "NM": "Nové Mesto nad Váhom",
    "NO": "Námestovo",
    "NZ": "Nové Zámky",
    "PE": "Partizánske",
    "PK": "Pezinok",
    "PN": "Piešťany",
    "PO": "Prešov",
    "PP": "Poprad",
    "PT": "Poltár",
    "PU": "Púchov",
    "RA": "Revúca",
    "RK": "Ružomberok",
    "RS": "Rimavská Sobota",
    "RV": "Rožňava",
    "SB": "Sabinov",
    "SC": "Senec",
    "SE": "Senica",
    "SI": "Skalica",
    "SK": "Snina",
    "SL": "Stará Ľubovňa",
    "SN": "Spišská Nová Ves",
    "SO": "Sobrance",
    "SP": "Stropkov",
    "SV": "Snina",
    "SA": "Šaľa",
    "TN": "Trenčín",
    "TO": "Topoľčany",
    "TR": "Turčianske Teplice",
    "TT": "Trnava",
    "TS": "Tvrdošín",
    "TV": "Trebišov",
    "VK": "Veľký Krtíš",
    "VT": "Vranov nad Topľou",
    "ZA": "Žilina",
    "ZC": "Žarnovica",
    "ZH": "Žiar nad Hronom",
    "ZM": "Zlaté Moravce",
    "ZV": "Zvolen"
}

ALERT_TYPES = {
    "burka": "burka",
    "dazd": "dazd",
    "hmla": "hmla",
    "nizke_teploty": "nizke_teploty",
    "poladovica": "poladovica",
    "snehove_jazyky_a_zaveje": "snehove_jazyky_a_zaveje",
    "snezenie": "snezenie",
    "vietor": "vietor",
    "vietor_na_horach": "vietor_na_horach",
    "vysoke_teploty": "vysoke_teploty"
}
